@startuml
class Persona{
+String cedula
+String nombre
+String direccion
+String correo
+String telefono
+void MostrarInformacion()
+void mostrarInformacionSinTelefono()
}

class Estudiante extends Persona{
+String carrera
+String nivel
+void MostrarInformacion(){overrride}
+int calculoEdad(int anio_nacimiento, int anio_actual)
}

class Docente extends Persona{
+String FacultadPertenece
+String HoraAsignadaClases
+void MostrarInformacion(){overrride}
+void mostrarInformacionSinTelefono(){overrride}
}

class Docente_linea extends Docente{
+String contrato
+void MostrarInformacion(){overrride}
+void mostrarInformacionSinTelefono(){overrride}
}

class Estudiante_Virtual extends Estudiante{
+String plataforma
+String tutore
+void MostrarInformacion(){overrride}
+int calculoEdad(int anio_nacimiento, int anio_actual){overrride}
}

class Estudiante_Presencial extends Estudiante{
+String hora_presencial
+String horario
+void MostrarInformacion(){overrride}
+int calculoEdad(int anio_nacimiento, int anio_actual){overrride}
}



@enduml